### PR TITLE
Updated help site copy

### PR DESCRIPTION
**Pull request by vonbearshark**
Removed reference to July-Dec 2020 data push
Added SASID references

Also removed `_site` build directory and related config.

## GitHub Issue
#1329

## Additional Context
Removed the `_site` directory. We should (and seem to) be using `/dist` for the build directory. The existing `_site` directory is outdated. If it's present in local dev Jekyll will end up in some confusing states. Added a `.gitignore` and updated the config accordingly. This all sounds a little dangerous, but I'm 99% sure this is right. Sorry for the diff.

### CODE REVIEW

**Review by JordanGuinn — APPROVED** [review]
All the non-text changes in here look sane to me - we'll just wanna make sure we're _extra_ wary during the next GitHub Pages deploy of this, to ensure we don't regress anything significant.  Which really just means being prepared to revert and redeploy if anything goes awry.

**Review by bamader — APPROVED** [review]
Yeah this all seems good to me. Just need to be careful with the deploys.

**Comment by bamader** [comment]
Built the Jekyll site to test that the new changes displayed correctly and appropriately, and everything looked totally good to me. I call this validated and ready to merge!

**Comment by vonbearshark** [comment]
Looks like we're all good 🚀 !

**Pull request merged**
